/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dongnaoedu_dnffmpegplayer_VideoPlayer */

#ifndef _Included_com_dongnaoedu_dnffmpegplayer_VideoPlayer
#define _Included_com_dongnaoedu_dnffmpegplayer_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dongnaoedu_dnffmpegplayer_VideoPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT jint JNICALL Java_com_dongnaoedu_dnffmpegplayer_VideoPlayer_render
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
